export const USER_ADD_WITH_SAME_ID = "Can't add same Id during adding user"
export const USER_ID_NOT_IN_LIST = "Can't find the user by id"
export const PARMS_ERROR = "Wrong params"
export const BOOK_ADD_WITH_SAME_ID = "Can't add same Id during adding book"
export const BOOK_ID_NOT_IN_LIST = "Can't find the book by id"
export const BOOK_IS_NOT_AVAILIABLE ="This book is not availiable"